version: '3.2'

services:

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/.data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: random
      MYSQL_ROOT_PASSWORD: "${PASSWORD:-password}"
    container_name: db-random
